### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by shalomvolchok** [denvned/isomorphic-relay-router#40]
It seems that memory usage, in the example todo app of this repo, grows with every request. After about 5,000 request, on my local computer, the app consistently crashes with process out of memory.

The star wars example from isomorphic-relay doesn't seem to have this issue. After 25,000 requests memory usage was still consistent.

Am I missing something simple here? I know a lot of work was done to make Relay state contextual and it seems like that has all been finished.

I've attached two graphs from logging process.memoryUsage() on each request. The first (steady) graph is from isomorphic-relay and the second graph is from isomorphic-relay-router.

![relay-isomorphic-mem](https://cloud.githubusercontent.com/assets/4439099/16714856/93229cd8-46d8-11e6-974b-1527491fc923.png)
![relay-isomorphic-router-mem](https://cloud.githubusercontent.com/assets/4439099/16714857/93253d62-46d8-11e6-932f-7d02d6e3858c.png)

**Comment by ntharim** [comment]
It's probably related to [this issue](https://github.com/facebook/relay/issues/754).

**Comment by tomconroy** [comment]
@nthtran following on from discussion in that thread – the problem has to do with relay using the container component as a cache key, and since `isomorphic-relay-router` creates a new instance of `QueryAggregator` in every request, that cache grows boundlessly.

I thought I had solved this here https://github.com/tomconroy/isomorphic-relay-router/commit/d03e3a54b9d14c2da34fe1153088c7467d6de452 – this works, but it was problematic when the server was processing concurrent requests.

@nthtran suggests we cache these QueryAggregator instances, keyed by the router location (?)

**Comment by ntharim** [comment]
My initial thought is after `match`ing we can get the `routes` array from `renderProps`. By using `path`s from the matched routes as the cache key, we can cache a `QueryAggregator` instance per route combination. @denvned you understand the internals much better, do you think this would be a good idea?

**Comment by KCraw** [comment]
@nthtran Won't you run into the same problems as @tomconroy regarding concurrent requests if they happen to be for the same path? Isn't a unique `QueryAggregator` instance per request a requirement for concurrency?

I think the problem here is with the use of `QueryAggregator` at all. I believe that `Relay.getQueries` is expecting a component class/constructor and not an instance of a component, which would make sense. Unfortunately, `QueryAggregator` implements the required static methods of `RelayContainer` as instance methods, and passing an instance as the Container works, but for the whole 'inevitably crash your production app through normal use' problem. It seems unlikely to find a scalable solution that involves passing instances.

The star wars example in isomorophic-relay obviously avoids this problem because it is passing  a constructor. Not sure how QueryAggregator could be made to work here...

**Comment by denvned** [comment]
I've just pushed a fix for this issue. I believe the fix is solid, but if it doesn't work for you please tell.

**Comment by KCraw** [comment]
Looks like an AggregateContainer is cached per unique route, and is only caching the fragment information, so can safely be shared between "concurrent" users requesting the same unique path. The params are still unique per request and handled by QueryAggregator. 

That is an extremely clever solution. Nice!

**Comment by rodrigopr** [comment]
Hi @denvned, thanks for taking a look into this issue and for the project as a whole, it's been super helpful to us.

Testing locally the new version it appears that the `queryCache` from `getRelayQueries.js` behaves as expected. But we still see a leak in `buildRQL.js` queryCache.
The cache is growing unbounded with instances of `wrappedQuery` (aparently [this one](https://github.com/relay-tools/react-router-relay/blob/5d3fe62188c60c02ffd8c40015328ca16a6b62e8/src/QueryAggregator.js#L87))

![](http://dsh.re/64876)

![](http://dsh.re/42c18)

should we reopen this?

**Comment by denvned** [comment]
> But we still see a leak in buildRQL.js queryCache.
> The cache is growing unbounded with instances of wrappedQuery

@rodrigopr It would be strange if it really happens, because `queryCache` in `buildRQL.js` is used only by the `buildRQL.Query` that is called only by `getRelayQueries` and only when there is a local cache miss. That means the cache of `buildRQL.Query` can grow only when the cache of `getRelayQueries` grows. So if there is no leak in `getRelayQueries` there cannot be a leak in `buildRQL.Query`.

Still cache of `buildRQL.Query` can grow big, and this is a problem of _react-router-relay_ in general, but not specifically of _isomorphic-relay-router_.

**Comment by rodrigopr** [comment]
Hmm, I'll have to investigate further.
On a quick look seems like getRelayQueries cache isn't growing beyond the number of routes ![](http://dsh.re/91d80).

Will report back if I find something. But as you said, the fix might be on react-router-relay.
Thanks :)

**Comment by denvned** [comment]
> On a quick look seems like getRelayQueries cache isn't growing beyond the number of routes

Yes, but there might be multiple queries per route, that's why the `buildRQL` cache might grow a bit faster than the `getRelayQueries` cache.

**Comment by shalomvolchok** [comment]
Looks great!! Testing locally with ab, stable after 275,000 requests... 
![screenshot from 2016-08-22 21 52 39](https://cloud.githubusercontent.com/assets/4439099/17861527/19962478-689a-11e6-9d95-5b5d5c5fcbc9.png)

**Comment by denvned** [comment]
@shalomvolchok Thank you for confirming!
